### ISSUE TITLE
Colorama escape objects not working on input() prompt on Windows

### ISSUE THREAD

**Issue by mrgou** [tartley/colorama#295] opened 2020-12-26 21:51 UTC
On Windows, contrary to Linux, this will not provide the expected results:

```python
In [1]: from colorama import Fore, Style, init

In [2]: init()

In [3]: my_string = 'abc'

In [4]: my_input = input(f'Enter input {Fore.GREEN}{Style.BRIGHT}{my_string}{Style.RESET_ALL}: ')
Enter input ←[32m←[1mabc←[0m:
```

However, this works fine;

```python
In [5]: print(f'Enter input {Fore.GREEN}{Style.BRIGHT}{my_string}{Style.RESET_ALL}: ')
Enter input abc:
```

**Comment by wiggin15** [comment] 2020-12-30 14:43
Duplicate of #103

**Closed by wiggin15** 2020-12-30 14:43 UTC
