### ISSUE TITLE
MacOS Background Color not resetting

### ISSUE THREAD

**Issue by ThePlasmaGuy** [tartley/colorama#120] opened 2017-01-19 17:16 UTC
I am attempting to change the background color at different parts throughout a string.  The desired effect I want is something like this:
<img width="715" alt="screen shot 2017-01-19 at 10 12 01 am" src="https://cloud.githubusercontent.com/assets/21127347/22117127/0919ecea-de30-11e6-9f5e-7b0e52634845.png">
(_photoshopped_)

However, when I test the code, this is what actually appears.
<img width="715" alt="2" src="https://cloud.githubusercontent.com/assets/21127347/22117155/22ba177e-de30-11e6-8af1-4aa9727e2dcf.png">

After researching this bug around the internet, I have determined that it is a pretty well known bug with macOS terminals.  There were several methods of fixing the issue, but none that I knew how to do in python, especially in regards to this library.  Thus, I am asking here if anyone knows a way to fix this background color bleed bug from within python in a way that works with the cross platform functionality of colorama.

Thanks for your help, 
TPG

**Comment by firebird631** [comment] 2017-03-02 13:24
Do you reset the style before the carriage return (\n) ?

**Comment by wiggin15** [comment] 2017-04-03 13:43
Hello @ThePlasmaGuy. Can you please post the code you used to produce this effect? I think that if you reset the style before the `\n` like @firebird631 suggested, the colors should appear correctly.

**Comment by wiggin15** [comment] 2017-09-11 20:28
I'm closing this ticket because I can't reproduce this. Also, this could be related to bright background not being reset correctly, which was fixed in #142. Please reopen this ticket if the problem persists.

**Closed by wiggin15** 2017-09-11 20:28 UTC
