### ISSUE TITLE
unicode variables printed out

### ISSUE THREAD

**Issue by ror6ax** [tartley/colorama#203] opened 2018-10-29 12:42 UTC
Hello! Some of my users report seeing `u'\x1b[96m` prepending text instead of line with coloured output.
I can't reproduce this bug on my machine but it since has been confirmed by others. No visible connection to OS/terminal/shell of something like that.

I asked all of them to run following snippet
```
import colorama
from colorama import Fore
print(Fore.BLUE + “Hello World”)
```
... and weirdly, in such case output is coloured as expected, no unicode symbols.

Could you please advice what may be the problem?

Thanks!

**Comment by ror6ax** [comment] 2018-11-08 10:43
Trying to get someone to answer if it's ok ;) 
ping @wiggin15

**Comment by tartley** [comment] 2018-11-08 21:10
Hi. Off the top of my head I do not know. Wild-ass theories to follow...

**Comment by tartley** [comment] 2018-11-08 21:10
Theory 1: This tickles a vague memory I had of a lurking bug I *knew* must exist in Colorama when I wrote the original code, but nobody ever complained about (which puzzled me.) It only recognizes a subset (one?) of all the valid escape sequences that can be prefixed to color codes. But now I come to look, this theory seems bogus, because (a) the sequence ror6ax quotes in his description above starts with the standard escape sequence `ESC[` where 'ESC' is a hex `1b` char. Plus, in 30 seconds of googling around, I now can't find any description of what the alternate escape sequences are. So ignore this paragraph, maybe? Sorry.

**Comment by tartley** [comment] 2018-11-08 21:14
Theory 2: I've forgotten almost everything about how colorama works by now, but could it be that colorama is converting stuff going to stdout into a utf8 string, and searching that string for ANSI codes. Perhaps this works fine when the output IS a utf8 string, but fails when the output is some other encoding? If so, perhaps we should be treating stdout as bytes, and searching for sequences of bytes that match the ANSI codes. It could be that colorama already does this, and I'm just misremembering. In which case, ignore this paragraph too.

**Comment by tartley** [comment] 2018-11-08 21:15
Passing thought 1: Obviously a reproduceable example would be valuable.

**Comment by tartley** [comment] 2018-11-08 21:19
@ror6ax . When the bug happens, does it happen for every code the program emits, or only for some? Does it happen every time that user runs your program? Does your program print color codes (etc) using colorama shortcuts like colorama.Fore.BLUE? Or does it use something else like blessings to produce the ANSI codes for colors etc?

**Comment by tartley** [comment] 2018-11-09 13:16
Oops, accidentally closed this. Reopened now.

**Comment by wiggin15** [comment] 2018-11-09 15:32
Sorry for not answering sooner. I was traveling. 
I am also not aware of any known issue that might cause this. I'm afraid without a minimal sample code that reproduces the problem it's going to be hard to find the cause, so a good start would be finding an environment where this happens and trying to isolate the code that causes this.

My wild theories:
1. the code `96m` they are seeing is `LIGHTBLUE_EX`, which is not a standard ANSI code. You can ask them to run the same sample with this code and see if it's converted or not.
2. Make sure colorama is initialized (and not more than once). init is missing in the sample code you provided.
3. The 'u' code they are seeing is specific to Python 2, but your snippet uses 'print' as a function (like in Python 3). When printing multiple arguments, like `print(arg1, arg2)` Python 2 will parse this as a tuple and the interpreter will print the "repr" of the string, which will include the `u` code and the ANSI codes unconverted. So check Python version and see if `print(Fore.BLUE + "Hello World", "foo")` produces the same problem.

**Comment by xcodz-dot** [comment] 2020-11-28 11:21
After importing colorama
Add this to your code
```python
colorama.init()
```

**Comment by xcodz-dot** [comment] 2020-11-28 11:21
Sorry if i am late, this issue is open

**Comment by tartley** [comment] 2020-11-29 16:55
Thanks @xcodz-dot, yes, you are absolutely right. Silly me.

Closing this since xcodz-dot's suggestion seems to explain the problem, and there has been no response from the original reporter.

Hugs, everyone.

**Closed by tartley** 2020-11-29 16:55 UTC

**Comment by iuriguilherme** [comment] 2022-11-27 23:14
I reproduced this: https://gist.github.com/iuriguilherme/196677d2bc95de343ba9f474e701b4ad#file-coloridacci-py-L308-L315

If you uncomment lines 309-315 and comment lines 301-307, it'll display the first 3 values correctly but the 3 last values which are floating points will display hex escapes instead of colors.

The portion where colorama is used is in the [function "colorize" at lines 161 to 189](https://gist.github.com/iuriguilherme/196677d2bc95de343ba9f474e701b4ad#file-coloridacci-py-L161-L189)

The very same code is just copy pasted from another script I had which display the colors correctly for floating points: [script](https://gist.github.com/iuriguilherme/a9ca8c5dc622a8f4f7ad1cd299bace16) [video](https://www.instagram.com/p/Ci3fX-SA53b/)
