### ISSUE TITLE
Colorama not working with input() in python 3.7.3, windows 10 build 17763.805

### ISSUE THREAD

**Issue by angus-y** [tartley/colorama#234] opened 2019-11-02 15:34 UTC
importing colorama and running colorama.init() does not work for input(), printing works but input no longer works with colored text. Is there a way to get around this?

**Comment by wiggin15** [comment] 2020-04-03 10:53
Please have a look at #103.

**Comment by wiggin15** [comment] 2020-12-30 14:44
Duplicate of #103

**Closed** 2022-07-29 12:20 UTC
