### ISSUE TITLE
colorama not working on input

### ISSUE THREAD

**Issue by JonathonRP** [tartley/colorama#138] opened 2017-07-18 16:02 UTC
i noticed that you have fixed this, but going back through the code and everything your fix was not in place. i fixed it for myself with the work around you provided. but thought you should know about this to have a fix for future versions. never mind, i didnt read the full post i see why it is the way it is now. you can just close this. ill keep an eye out for the new version with the correct fixes

**Comment by Ghostboy-287** [comment] 2017-08-30 14:58
i have this problem 
colorama works fine with print but dont work with input  on windows 

@JonathonRP  can you tell us how did you fix that, please? 
while waiting @tartley answer :)

**Comment by tartley** [comment] 2017-09-01 01:44
Hi. I retired from this project, @wiggin15 is in charge around these parts these days, and has been doing lots of sterling work.

I don't, offhand, know how to fix this. Do you mean your Python program is doing an `input()` (or for Python2, `raw_input()`), and the text the user types is not colored?

If I remember rightly, `input()` accepts a prompt that it prints before the text the user types. What if you put some control codes in that prompt string? Does the color left active at the end of that affect the subsequent typing?

**Comment by wiggin15** [comment] 2017-09-02 11:01
We are aware that `input` doesn't work with colorama on Python 3.5+. There is already an open issue about this, #103. We traced it back to a bug with Python itself and the proposed workaround was not good enough. I currently don't have a solution for this.

**Comment by wiggin15** [comment] 2017-09-11 20:27
I'm closing this ticket as a duplicate of #103.

**Closed by wiggin15** 2017-09-11 20:27 UTC

**Comment by blob76363** [comment] 2022-03-12 13:13
So is it any way fix

**Comment by tartley** [comment] 2022-03-12 19:14
@blob76363 For the most up-to-date advice, see the conversation on the linked issue #103
