### ISSUE TITLE
Colorama not working with input(...)

### ISSUE THREAD

**Issue by ghost** [tartley/colorama#252] opened 2020-03-18 17:03 UTC
System: Windows 10
Shell: cmd.exe
Python: 3.8.1
Colorama: 0.4.3

For example:

from colorama import Fore, init
init()
input(Fore.RED + "test")
This prints ←[31mtest instead of of "test" in red.

The weird thing is, it does work in the VSC terminal. Tried looking for solutions could not find any working

**Comment by wiggin15** [comment] 2020-04-03 10:53
Please have a look at #103

**Comment by wiggin15** [comment] 2020-12-30 14:43
Duplicate of #103

**Closed by wiggin15** 2020-12-30 14:43 UTC
