### ISSUE TITLE
Support the full set of control codes in Ansi2Win32

### ISSUE THREAD

**Issue by KOLANICH** [tartley/colorama#149] opened 2017-11-01 09:27 UTC
For example the codes generated by https://github.com/KOLANICH/RichConsole are not supported, even such basic ones as adding blinking.

**Comment by wiggin15** [comment] 2017-11-01 10:11
This is a duplicate of #38 (and other tickets opened about support for more ANSI codes). Please see this comment in the ticket: https://github.com/tartley/colorama/issues/38#issuecomment-128834060

**Closed by wiggin15** 2017-11-01 10:11 UTC
