### ISSUE TITLE
Why doesn't it works with 'input' method under Windows?

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [tartley/colorama#124] opened 2017-03-20 18:08 UTC
Under linux, not only the 'print' method but 'input' can render color, while Windows only works with 'print'.
I think it's better to keep them coincident.

**Comment by dougthor42** [comment] 2017-03-27 21:09
Duplicate of #103. Please see that issue for more information.

**Comment by wiggin15** [comment] 2017-04-03 13:45
Closing as duplicate.

**Closed by wiggin15** 2017-04-03 13:45 UTC
