### ISSUE TITLE
request update regarding 'colorama not working with input()

### ISSUE THREAD

**Issue by oseda68** [tartley/colorama#261] opened 2020-05-23 13:26 UTC
Hi, have  Pycharm with windows 10 . I have the same issue with colorama. Ive been reading user comments from years ago on this. Has there been any resolution to address this problem for 2020?
Paul

**Comment by oseda68** [comment] 2020-05-23 14:15
print(Fore.BLUE +'           Continue? y or n: c for breaker chart\n', end = '')  
   ans = input().lower()
This does work,
 submitted by others
Is this a good solution?

**Comment by Muhimen123** [comment] 2020-06-11 09:49
```python
import colorama
colorama.init()
print(colorama.Fore.GREEN)
number = input("Enter a number here: ")
```

This code works for me

**Comment by wiggin15** [comment] 2020-12-30 14:43
Duplicate of #103

**Closed by wiggin15** 2020-12-30 14:43 UTC
