### ISSUE TITLE
Colorama does not work with all font types

### ISSUE THREAD

**Issue by DovahRahDoLu** [tartley/colorama#78] opened 2015-11-05 18:00 UTC
I would like to have a list of which fonts actually work with colorama for python 3.4

**Comment by tartley** [comment] 2015-11-05 20:15
Hey there.

I'm not aware that font choices should cause any problem.

In order for anyone to help, we'll need a more detailed description of the problem. Can you carefully describe a scenario that doesn't do what you expect? Include detailed versions of your operating system, Python version, Colorama version, the terminal emulator you are using (e.g. Window's standard 'cmd.exe'), the precise details of the fonts you are trying to use, the Python code you are executing, and what exactly it does, and what you expect to happen instead. Can you reduce that Python code to a minimal reproduction of the problem? Many thanks.

**Comment by wiggin15** [comment] 2016-01-09 19:10
I am also not aware of font issues. I'm closing this issue due to no reply.

**Closed by wiggin15** 2016-01-09 19:10 UTC
