### ISSUE TITLE
ansi.clear_screen() turn background gray on Windows

### ISSUE THREAD

**Issue by BookOwl** [tartley/colorama#89] opened 2016-03-04 19:42 UTC
On windows, running `print(colorama.ansi.clear_screen())` turns my console into this:
![capture](https://cloud.githubusercontent.com/assets/13385064/13538200/261e9f9a-e217-11e5-8c5d-8a91e7918ea2.PNG)
If I then run `cls`, the console turns back to normal:
![capture](https://cloud.githubusercontent.com/assets/13385064/13538221/489e8224-e217-11e5-8944-1709caa1e16b.PNG)

**Comment by wiggin15** [comment] 2016-05-30 06:56
Hi. I can't reproduce your issue, but I can reproduce something similar by running:
{noformat}
print colorama.Back.WHITE + colorama.ansi.clear_screen()
{noformat}
The clear screen function doesn't "reset" the console properties before clearing the screen. Perhaps fixing this bug will solve your issue too.

**Comment by wiggin15** [comment] 2017-09-11 20:25
I'm closing this ticket because I can't reproduce this. Also, this could be related to bright background not being reset correctly, which was fixed in #142. Please reopen this ticket if the problem persists.

**Closed** 2017-09-11 20:26 UTC
Labels: bug
