### ISSUE TITLE
Py2x confilict pyreadline - tab: complete option ..

### ISSUE THREAD

**Issue by b3mb4m** [tartley/colorama#92] opened 2016-04-02 13:40 UTC
If we call colorama on py2x, 

`from colorama import init` 
`init(autoreset=True)`

that broke(init function) readline tab-complete option, on 3x working smoothly.Any idea how to fix it or just why that happen on just py2x ?

**Comment by wiggin15** [comment] 2016-04-06 18:46
Thanks for reporting this. We are aware of this problem but don't have a fix. It appears to be a Python issue that was fixed in Python 3. See issue #52.
I'm closing this ticket as a duplicate of #52.

**Closed by wiggin15** 2016-04-06 18:46 UTC

**Comment by b3mb4m** [comment] 2016-04-08 03:19
Let me one more question, is there no way to fix on 2x ? If you can refer 3x patch link maybe i can implement same thing to 2x ..

**Comment by wiggin15** [comment] 2016-04-09 13:07
According to the link in #52 (https://bugzilla.redhat.com/show_bug.cgi?id=841152):

> Looking at Python 3 way, the logic of finding out whether stdout is a tty is completely rewritten [1] and I think that Python 2 version would need significant adjustments to work this way."

I'm afraid I don't have further resources or insights about this.
