### ISSUE TITLE
colorama doesn't play well with pytest

### ISSUE THREAD

**Issue by robmoggach** [tartley/colorama#82] opened 2016-01-10 02:35 UTC
When I run tests on a package using colorama I get this lovely traceback:

    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
        func(*targs, **kargs)
      File "/usr/local/lib/python2.7/site-packages/colorama/initialise.py", line 19, in reset_all
        AnsiToWin32(orig_stdout).reset_all()
      File "/usr/local/lib/python2.7/site-packages/colorama/ansitowin32.py", line 67, in __init__
        strip = conversion_supported or not is_a_tty(wrapped)
      File "/usr/local/lib/python2.7/site-packages/colorama/ansitowin32.py", line 17, in is_a_tty
        return hasattr(stream, 'isatty') and stream.isatty()
    ValueError: I/O operation on closed file
    Error in sys.exitfunc:

Removing colorama fixes the problem...

**Comment by wiggin15** [comment] 2016-01-10 10:35
colorama 0.3.6 was released yesterday with a fix for this issue. Are you using the latest version?

**Comment by robmoggach** [comment] 2016-01-10 14:14
Stack trace is from Travis running a Travis and py.test test so if you've pushed to PyPi then yes -

**Comment by wiggin15** [comment] 2016-01-10 16:28
The new version is on pypi and the line that fails:

     File "/usr/local/lib/python2.7/site-packages/colorama/ansitowin32.py", line 67, in __init__
        strip = conversion_supported or not is_a_tty(wrapped)

has been changed - it's not the same as the one on pypi. Can you please check the settings of your travis build to see why it's not using the latest version?

**Comment by blueyed** [comment] 2016-01-22 21:57
Seems to be a dupe of https://github.com/tartley/colorama/issues/81 then really.

**Comment by blueyed** [comment] 2016-01-22 22:17
Maybe you are seeing a new error now? #84

**Comment by wiggin15** [comment] 2016-01-23 14:11
@robmoggach does this still reproduce? If it does, can you please link to the Travis build that fails?

**Comment by robmoggach** [comment] 2016-01-23 17:21
Sorry no - removed it as a dependency for my rushed project 

Robert Moggach
Sr. VFX Supervisor | Flame Artist
http://moggach.com
(310) 773-1793

**Comment by wiggin15** [comment] 2016-01-23 19:20
I see. Is it ok if I close this ticket, then? I can't reproduce this.

**Comment by robmoggach** [comment] 2016-01-23 19:49
Yup go for it

**Closed** 2016-01-23 20:33 UTC
